# Turns every file under ui/ into a Win32 RCDATA resource so the executable
# can serve its own interface without an accompanying folder.
#
# Generates two files in the build tree:
#   ui_resources.rc   -- the resource script MSVC compiles into the binary
#   UiResources.cpp   -- a lookup table of {virtual path, resource id, mime}
#
# Usage:
#   embed_ui_directory("${CMAKE_CURRENT_SOURCE_DIR}/ui" RC_VAR CPP_VAR)

function(_ui_mime_for_extension EXT OUT_VAR)
    string(TOLOWER "${EXT}" EXT)
    if(EXT STREQUAL ".html" OR EXT STREQUAL ".htm")
        set(mime "text/html")
    elseif(EXT STREQUAL ".css")
        set(mime "text/css")
    elseif(EXT STREQUAL ".js" OR EXT STREQUAL ".mjs")
        set(mime "application/javascript")
    elseif(EXT STREQUAL ".json")
        set(mime "application/json")
    elseif(EXT STREQUAL ".svg")
        set(mime "image/svg+xml")
    elseif(EXT STREQUAL ".png")
        set(mime "image/png")
    elseif(EXT STREQUAL ".jpg" OR EXT STREQUAL ".jpeg")
        set(mime "image/jpeg")
    elseif(EXT STREQUAL ".webp")
        set(mime "image/webp")
    elseif(EXT STREQUAL ".ico")
        set(mime "image/x-icon")
    elseif(EXT STREQUAL ".woff2")
        set(mime "font/woff2")
    elseif(EXT STREQUAL ".woff")
        set(mime "font/woff")
    elseif(EXT STREQUAL ".ttf")
        set(mime "font/ttf")
    else()
        set(mime "application/octet-stream")
    endif()
    set(${OUT_VAR} "${mime}" PARENT_SCOPE)
endfunction()

function(embed_ui_directory UI_DIR OUT_RC_VAR OUT_CPP_VAR)
    # CONFIGURE_DEPENDS re-runs the glob on build, so adding a file to ui/
    # does not require a manual re-configure.
    file(GLOB_RECURSE ui_files CONFIGURE_DEPENDS RELATIVE "${UI_DIR}" "${UI_DIR}/*")

    if(NOT ui_files)
        message(FATAL_ERROR "embed_ui_directory: no files found under ${UI_DIR}")
    endif()

    set(rc_body "// Generated by cmake/EmbedUi.cmake -- do not edit.\n")
    set(table_body "")
    set(next_id 1000)
    set(embedded_count 0)

    foreach(rel IN LISTS ui_files)
        if(IS_DIRECTORY "${UI_DIR}/${rel}")
            continue()
        endif()

        math(EXPR next_id "${next_id} + 1")
        get_filename_component(ext "${rel}" EXT)
        _ui_mime_for_extension("${ext}" mime)

        # Keep CMake's forward slashes: rc.exe accepts them, which avoids the
        # backslash-escaping rules entirely and survives spaces in the path.
        string(APPEND rc_body "${next_id} RCDATA \"${UI_DIR}/${rel}\"\n")
        string(APPEND table_body "    { \"${rel}\", ${next_id}, L\"${mime}\" },\n")
        math(EXPR embedded_count "${embedded_count} + 1")
    endforeach()

    set(rc_path "${CMAKE_CURRENT_BINARY_DIR}/ui_resources.rc")
    set(cpp_path "${CMAKE_CURRENT_BINARY_DIR}/UiResources.cpp")

    file(WRITE "${rc_path}" "${rc_body}")
    file(WRITE "${cpp_path}"
"// Generated by cmake/EmbedUi.cmake -- do not edit.
#include \"UiResources.h\"

const UiResource kUiResources[] = {
${table_body}};

const size_t kUiResourceCount = sizeof(kUiResources) / sizeof(kUiResources[0]);
")

    message(STATUS "Embedding ${embedded_count} UI files into the executable")

    set(${OUT_RC_VAR} "${rc_path}" PARENT_SCOPE)
    set(${OUT_CPP_VAR} "${cpp_path}" PARENT_SCOPE)
endfunction()
